{{- if .Values.securityPolicy.enabled }}
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: {{ .Values.securityPolicy.securityPolicyName }}
  namespace: {{ .Values.appNamespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.securityPolicy.podName }}
  securityGroups:
    groupIds:
      {{ toYaml .Values.securityPolicy.spec.securityGroups.groupIds | indent 6 }}
{{- end }}
