{{- if .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.secrviceAccountName }}
  namespace: {{ .Values.appNamespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.arn }}
{{- end }}
